### See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk:
  - oraclejdk8

language: scala

sbt.version:
  - 1.0.3

scala:
   - 2.12.4

# Use container-based infrastructure
sudo: false

